package verkehrschaos;


/**
* verkehrschaos/ELocationInUse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Sonntag, 5. April 2015 16:48 Uhr MESZ
*/

public final class ELocationInUse extends org.omg.CORBA.UserException
{
  public String msg = null;

  public ELocationInUse ()
  {
    super(ELocationInUseHelper.id());
  } // ctor

  public ELocationInUse (String _msg)
  {
    super(ELocationInUseHelper.id());
    msg = _msg;
  } // ctor


  public ELocationInUse (String $reason, String _msg)
  {
    super(ELocationInUseHelper.id() + "  " + $reason);
    msg = _msg;
  } // ctor

} // class ELocationInUse
