package verkehrschaos;


/**
* verkehrschaos/TruckCompany.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from verkehrschaos.idl
* Sonntag, 5. April 2015 16:47 Uhr MESZ
*/

public interface TruckCompany extends TruckCompanyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TruckCompany
